### ISSUE TITLE
[request] Mobile support

### ISSUE THREAD

**Issue by trusktr** [davidjamesstone/noide#7]
Interesting concept! I tried it on android (using Termux) but the view isn't optimized for Mobile at all. That would be neat!

**Comment by davidjamesstone** [comment]
Hi there,

Mobile would be a nice feature and wouldn't be difficult to implement given it's based on bootstrap.
The problem is that editing code on a mobile isn't that easy and it wasn't really a consideration originally.

I have another, better more evolved version of `noide` called `vsd` https://github.com/davidjamesstone/vsd.

This did have mobile in mind from the beginning and may be a better option for you.
It also features a OSX Finder style file browser and a dashboard home page thingy.
You can ignore all the database schema designer stuff it has.

Let me know if you try it and what you think.

Cheers

Dave

**Comment by trusktr** [comment]
Cool, that's much better! The only problem is when I press inside a text area to begin editing, the keyboard covers the text area and it's not possible to scroll it into view, so I can't see what i'm typing.

**Comment by davidjamesstone** [comment]
I have the same issue on my Samsung Note 2 but not iOS.

Try scrolling up/down at the far right edge of the editor - that works for me.

I think it's a bug in the `ace` editor on Android.

Like I say, editing code on a mobile isn't something you'd want to do for too long - it's not a great experience. If you have any suggestions to improve it let me know. I considered using a different editor for mobile, possibly just a simple glorified text area would be better.

**Comment by trusktr** [comment]
I am able to reveal only the tab bar, but can scroll any more (I think maybe the text area height has become zero, but haven't checked).

> it's not a great experience.

Yeah, there doesn't seem to be any web-based editor in existence that cares to handle mobile (I tried Ace, CodeMirror, etc). :( Someone needs to make one! I was thinking about doing so once my 3D engine is complete (using only it's 2D subset for text).

**Comment by davidjamesstone** [comment]
Really neat library that. I noticed you started out using famous then decided to build your own.

I liked the look of famous in it's early days (periodic table globe if you remember that?) but I haven't kept up with it's progress. Last time I looked in it seemed to have changed direction and maybe interest in it has dropped off?

I'm interested in what made you decided to build your own.

**Comment by trusktr** [comment]
One of the biggest reasons was a lack of open development from Famous. Compare it to Three.js, which is truly open for example.
